# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-11 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('content', models.TextField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=140)),
            ],
        ),
    ]
