# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='comments_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articles',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articles',
            name='user_name',
            field=models.CharField(default='admin', max_length=140),
        ),
    ]
