# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171213_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('user_id', models.IntegerField(default=0)),
                ('user_name', models.CharField(default='Неизвестный', max_length=140)),
            ],
        ),
        migrations.AlterField(
            model_name='articles',
            name='user_name',
            field=models.CharField(default='Неизвестный', max_length=140),
        ),
    ]
