# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171213_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='article_id',
            field=models.IntegerField(default='-1'),
        ),
    ]
