# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 20:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comments_article_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='articles',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
