# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171213_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='user',
            new_name='user_id',
        ),
    ]
