# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 21:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171213_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
