# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-13 22:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20171213_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user_name',
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='article_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Articles'),
        ),
    ]
