# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20171213_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.CharField(default='Неизвестный пользователь', max_length=140),
        ),
    ]
